build:
  binary: task
  main: cmd/task/task.go
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - 386
    - amd64
  ignore:
    - goos: darwin
      goarch: 386

archive:
  name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"

  format_overrides:
    - goos: windows
      format: zip

release:
  draft: true

fpm:
  vendor: Task
  homepage: https://github.com/go-task/task
  maintainer: Andrey Nering <andrey.nering@gmail.com>
  description: Simple task runner written in Go
  license: MIT
  formats:
    - deb
    - rpm
