#!/bin/sh
set -x
set +e

clear
echo

git subtree add --prefix services/dog/src https://github.com/dogtools/dog master --squash
git subtree add --prefix services/myke/src https://github.com/goeuro/myke master --squash
git subtree add --prefix services/zeus/src https://github.com/dreadl0ck/zeus master --squash
git subtree add --prefix services/go-task/src https://github.com/go-task/task master --squash
git subtree add --prefix services/cayley/src https://github.com/cayleygraph/cayley master --squash
git subtree add --prefix services/abrain/src https://github.com/arbrain/abrain master --squash
git subtree add --prefix services/dgraph/src https://github.com/dgraph-io/dgraph master --squash
git subtree add --prefix services/go-url-fuzzer/src https://github.com/mtojek/go-url-fuzzer master --squash
git subtree add --prefix services/fluided/src https://github.com/theskyinflames/fluided master --squash
git subtree add --prefix services/scipipe/src https://github.com/scipipe/scipipe master --squash
git subtree add --prefix services/scipipe/src https://github.com/flowbase/flowbase master --squash
git subtree add --prefix services/rdf2smw/src https://github.com/rdfio/rdf2smw master --squash
git subtree add --prefix services/goflow/src https://github.com/abferm/goflow master --squash
git subtree add --prefix services/packman/src https://github.com/jboursiquot/packman master --squash
git subtree add --prefix services/bandmaster/src https://github.com/znly/bandmaster master --squash
git subtree add --prefix services/r2g/src https://github.com/HamiTrip/R2G master --squash
git subtree add --prefix services/tusk/src https://github.com/rliebz/tusk master --squash
git subtree add --prefix services/machinery/src https://github.com/RichardKnop/machinery master --squash
git subtree add --prefix services/nut/src https://github.com/matthieudelaro/nut master --squash
git subtree add --prefix services/gogurt/src https://github.com/AlexandreCarlton/gogurt master --squash