#!/bin/sh
set -x
set +e

clear
echo

git subtree add --prefix services/dog/src github.com/dogtools/dog master --squash
git subtree add --prefix services/myke/src github.com/goeuro/myke master --squash
git subtree add --prefix services/zeus/src github.com/dreadl0ck/zeus master --squash
git subtree add --prefix services/go-task/src github.com/go-task/task master --squash
